Alpha/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Nile.urls')),
    path('', include('Administrator.urls')),
     path('', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
]

Nile/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
       path('', views.Home, name="home"),
       path('listings/', views.Products, name="listings"),
       path('checkout/', views.Checkout, name="checkout"),
       path('profile/', views.Profile, name="profile"),
       path('pricing/', views.Subscribe, name="subscribe"),
       path('login/', views.Login,  name="login"),
       path('register/', views.Register, name="register"),
       path('quit/', views.Escape, name="escape" ),
       path('blank/', views.Blank, name="blank"),
       path('uplod/new/', views.productupload.as_view(), name="product-create"),
       path('post/<str:slug>/', views.postdetails.as_view(), name="product-detail"),
       path('images/', views.Vision, name="mistakes"),
       path('colors/', views.Color, name="color" ),
       path('Howler/', views.Howler, name="howler"),
       path('specifications/', views.Patten, name="patten"),
       path('activate/', views.Activate, name="activate"),
       path('settings/', views.Settings, name="settings"),
       path('review/<str:slug>/', views.Review, name="review"),
       path('message/', views.Message_In, name="message"),
       path('content/<str:subject>/', views.Contented, name="contented"),
       path('cart/<str:slug>/', views.Mycart, name="cart"),
       path('wishlist/<str:slug>/', views.Mywishlist, name="wishlist"),
       path('viewcart/', views.Viewcart, name="viewcart"),
       path('viewwish/', views.Viewwish, name="viewwish"),
       path('cartdelete/<str:slug>/', views.Delcart, name="catdelte"),
       path('wishdelete/<str:slug>/', views.Delwish, name="wishdelte"),
       path('request/<str:slug>/', views.Request, name="request"),
       path('demand/', views.Demand, name="demand"),
       path('orders/', views.Orders, name="orders"),
       path('shop/<str:vessel>/', views.Shop, name="shop"),
       path('edit-store/<str:vessel>/', views.Amend, name="amend"),
       path('silver/', views.Silver, name="silver"),
       path('platinum/', views.Platinum, name="platinum"),
       path('titanium/', views.Titanium, name="titanium"),
       path('wallet/', views.Wallet, name="wallet"),
       path('withdraw/', views.Withdraw, name="withdraw"),
       path('silverMin/', views.Silver_Min, name="silvermin"),
       path('silverPro/', views.Silver_Pro, name="silverpro"),
       path('platinumMin/', views.Platinum_Min, name="platinumin"),
       path('platinumPro/', views.Platinum_Pro, name="platinumpro"),
       path('titaniumMin/', views.Titanium_Min, name="titaniummin"),
       path('titaniumPro/', views.Titanium_Pro, name="titaniumpro"),
       path('titaniumEnter/', views.Titanium_Enter, name="titaniumenter"),
       path('professinal/', views.Professinal, name="professinal"),
       path('erise-test/<str:vessel>/', views.Erise_text, name="erisetext"),
       path('contacts/', views.Contact_In, name="contact"),
       path('erise-contact/<str:vessel>/', views.Contact_Out, name="erisecontact"),
       path('create-contact/<str:vessel>/', views.Contact_Set, name="createcontact"),
       path('squeezes/', views.Listing, name="squeeze"),
       path('loan/', views.Loan, name="loan"),
       path('deletorder/<str:vessel>/', views.Order_Delete, name="orderdelete"),
       path('requestdelete/<str:vessel>/', views.Demand_Delete, name="requestdelete"),
       path('vieworder/<str:vessel>/', views.Vieworder, name="vieworder"),
       path('demandaccept/<str:vessel>/', views.Demand_Accepted, name="demandaccept"),
       path('shipping/<str:vessel>/', views.Shipping, name="shipping"),
       path('removeshiping/<str:vessel>/', views.Shipping_Remove, name="removeshiping"),
       path('orderprocess/', views.Orderprocess, name="orderprocess"),
       path('loancreate/', views.Loan_create, name="loancreate"),
       path('loanbase/<str:vessel>/', views.Loanbase, name="loanbase"),
       path('media/', views.Movies, name="moviesin"),
       path('moviescontent/', views.Movie_View, name="movielist"),
       path('moviedetails/<str:vessel>/', views.Movies_Details, name="moviedetail"),
       path('moviessoftwaregames/', views.Movies_Software_Games, name="mogasa"), 
       path('mainsetting/', views.Mainsetting, name="mainsetting"),
       path('search/', views.Search_View),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Nile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.dispatch import receiver
from PIL import Image
from django.core.validators import URLValidator
from django.utils.timezone import now
from django.db.models import Sum, F, FloatField

# Create your models here.

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avater = models.ImageField(default='avater.jpg', upload_to='profile/', null=True)
    about = models.TextField(default="@Please Update Your Profile To Access Market",  null=True)
    phone = models.CharField(max_length=255, default="UNKNOWN", editable=True, null=True)
    subscription = models.CharField(default="Titanium", max_length=255, null=True)
    duration = models.IntegerField(default=15, null=True)
    terminate = models.DateField(auto_now=False, auto_now_add=False, default=now, blank=True )
    entirety = models.IntegerField(default=0, null=True)
    verified = models.BooleanField(default=False)
    professional = models.BooleanField(default=False)
    software = models.BooleanField(default=False)
    ended = models.DateField(auto_now=False, auto_now_add=False, default=now, blank=True)
    institute = models.CharField(max_length=255, default="UNKNOWN", editable=True, null=True)
    region = models.CharField(max_length=255, default="UNKNOWN",  editable=True, null=True)
    country = models.CharField(max_length=255, default="UNKNOWN", editable=True, null=True) 

    def __str__(self):
        return str(self.user)
        #return self.user.username + "Client" DecimalField(decimal_places=2)
        #return f"{self.user.username} Client"
    def save(self, force_insert = False, force_update = False, using = None):
        super().save()

        img = Image.open(self.avater.path)

        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.avater.path)
        

class Product(models.Model):
    title = models.CharField(max_length=255, editable=True, null=True) 
    price = models.FloatField()
    price_cancel = models.FloatField()
    sample = models.CharField(max_length=450, editable=True, null=True) 
    description = models.TextField()
    category = models.CharField(max_length=255, editable=True, null=True) 
    kind = models.CharField(max_length=25, editable=True, null=True) 
    availability = models.CharField(max_length=55, editable=True, null=True) 
    image = models.ImageField(default='avater.jpg', upload_to='product/', blank=True, null=True)
    slug = models.SlugField(unique=True)
    active = models.BooleanField(default=True)
    country = models.BooleanField(default=False)
    zone = models.BooleanField(default=False)
    institute = models.BooleanField(default=False)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=255, editable=True, null=True) 
    terminate = models.DateField(auto_now=False, auto_now_add=False, null=True)

    def __str__(self):
        return self.slug
   
    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'slug': self.slug})

class vision(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    image1 = models.ImageField(default='product.jpg', upload_to='product/', blank=True, null=True)
    image2 = models.ImageField(default='product.jpg', upload_to='product/', blank=True, null=True)
    image3 = models.ImageField(default='product.jpg', upload_to='product/', blank=True, null=True)
    image4 = models.ImageField(default='product.jpg', upload_to='product/', blank=True, null=True)
    image5 = models.ImageField(default='product.jpg', upload_to='product/', blank=True, null=True)
   
    def __str__(self):
        return str(self.product)
    

class size(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, default="None", editable=True, null=True, blank=True) 
    fild1 = models.CharField(max_length=25, default="None", editable=True, null=True, blank=True) 
    fild2 = models.CharField(max_length=25, default="None", editable=True, null=True, blank=True) 
    fild3 = models.CharField(max_length=25, default="None", editable=True, null=True, blank=True) 
    fild4 = models.CharField(max_length=25, default="None", editable=True, null=True, blank=True) 
    fild4 = models.CharField(max_length=25, default="None", editable=True, null=True, blank=True) 
   
    def __str__(self):
        return str(self.product)

class color(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, default="None", editable=True, null=True, blank=True) 
    color1 = models.CharField(max_length=25, default="None", editable=True, null=True, blank=True) 
    color2 = models.CharField(max_length=25, default="None", editable=True, null=True, blank=True) 
    color3 = models.CharField(max_length=25, default="None", editable=True, null=True, blank=True) 
    color4 = models.CharField(max_length=25, default="None",  editable=True, null=True, blank=True) 
    color4 = models.CharField(max_length=25, default="None", editable=True, null=True, blank=True) 
   
    def __str__(self):
        return str(self.product)

class pattern(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    tab1 = models.CharField(max_length=25, default="Not Found", editable=True, null=True, blank=True) 
    tab2 = models.CharField(max_length=25, default="Not Found", editable=True, null=True, blank=True) 
    tab3 = models.CharField(max_length=25, default="Not Found", editable=True, null=True, blank=True) 
    tab4 = models.CharField(max_length=25, default="Not Found",  editable=True, null=True, blank=True) 
    tab5 = models.CharField(max_length=25, default="Not Found", editable=True, null=True, blank=True) 
    det1 = models.CharField(max_length=25, default="Not Found", editable=True, null=True, blank=True) 
    det2 = models.CharField(max_length=25, default="Not Found", editable=True, null=True, blank=True) 
    det3 = models.CharField(max_length=25, default="Not Found", editable=True, null=True, blank=True) 
    det4 = models.CharField(max_length=25, default="Not Found",  editable=True, null=True, blank=True) 
    det5 = models.CharField(max_length=25, default="Not Found", editable=True, null=True, blank=True)

    def __str__(self):
        return str(self.product)




class review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment = models.CharField(max_length=255, default="Not Found", editable=True, null=True, blank=True)
    rating  = models.PositiveIntegerField(default=1)
    time = models.DateField(auto_now_add=True, null=True)
 

class Post(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='post_receiver', db_column='receiver')
    vendor = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='post_sender', db_column='sender')
    title = models.CharField(max_length=255, default="Chat With Robot", editable=True, null=True, blank=True)
    slug = models.SlugField(unique=True, default="Chat-With-Robot")

    def __str__(self):
        return str(self.slug)



class Message(models.Model):
    subject = models.ForeignKey(Post, on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='message_receiver', db_column='receiver')
    vendor = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='message_sender', db_column='vendor')
    texting = models.TextField(default="Chat With Robot")
  
    def __str__(self):
        return str(self.subject)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.product)


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.product)



class Stipulate(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    seller = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='stipulate_seller', db_column='seller')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    marked = models.CharField(max_length=250, default="None", unique=True)
    terminate = models.BooleanField(default=False)
    size = models.CharField(max_length=250, default="None", editable=True, null=True, blank=True) 
    size01 = models.CharField(max_length=250, default="None", editable=True, null=True, blank=True)
    color = models.CharField(max_length=250, default="None", editable=True, null=True, blank=True) 
    color01 = models.CharField(max_length=250, default="None", editable=True, null=True, blank=True)
    extent  = models.PositiveIntegerField(default=1)
    accepted = models.BooleanField(default=False)
    shipping = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    payment = models.BooleanField(default=False)
    charge = models.FloatField(default=0)
    reference = models.CharField(max_length=250, default="None")
    slot = models.DateTimeField(default=now)

    def __str__(self):
        return str(self.marked)

    @property
    def get_total(self):
        total = self.product.price * self.extent
        return total

    @property
    def get_total_items(self):
        total = self.__class__.objects.all().aggregate(sum_all=Sum('extent')).get('sum_all')
        return total

    @property
    def get_total_price(self):

templates/Nile/product_form.html
{% extends 'core/base.html' %}

{% block title %} Blank Page {% endblock %}

{% load static %}

{% block body %} 

{% include 'core/navigation.html' %}
    

	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="#">Home</a></li>
				<li class="active">Blank</li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
		   <div class="row">

		        <div class="col-md-2">ads
	         	</div>

				<div class="col-md-8">

                {% for message in  messages %}
	            <div class="alert alert-success text-center">
	              {{message}}
	            </div>
				{% endfor %}

		<div class="contact_title">
            <h2>Product Listing</h2>
            <p>Follow the steps below to create email account enjoy the great mail.com emailing experience. Vivamus tempus risus vel felis condimentum, non vehicula est iaculis.</p>
          </div>

  <form  method="POST" action="."  enctype="multipart/form-data" class="p-5 bg-white border">
  {% csrf_token %}
  {{form.media}}


      <div class="row form-group">
	        <div class="col-md-12 mb-3 mb-md-0">
	         <label class="font-weight-bold" for="fullname">Enter Title <span style="color : red; font-size: 16px;" >*</span> </label>
	        {{form.title}}
	      </div>
	    </div>

       <div class="row form-group">
	        <div class="col-md-12 mb-3 mb-md-0">
	         <label class="font-weight-bold" for="fullname">Enter Actual Price <span style="color : red; font-size: 16px;" >*</span> </label>
	         {{form.price}}
	      </div>
	    </div>

       <div class="row form-group">
	        <div class="col-md-12 mb-3 mb-md-0">
	         <label class="font-weight-bold" for="fullname">Enter Discounted Price <span style="color : red; font-size: 16px;" >*</span> </label>
	         {{form.price_cancel}}
	      </div>
	    </div>



      <div class="row form-group">
	      <div class="col-md-12 mb-3 mb-md-0">
	          <label class="font-weight-bold" for="fullname">Enter Sample Description <span style="color : red; font-size: 16px;" >*</span> </label>
	     	   <textarea name="sample"   id="id_sample" cols="30" rows="5" class="form-control" placeholder="Full Product Description" required></textarea>
	       </div>
	     </div>

      <div class="row form-group">
	      <div class="col-md-12 mb-3 mb-md-0">
	          <label class="font-weight-bold" for="fullname">Enter Description <span style="color : red; font-size: 16px;" >*</span> </label>
	           {{form.description}}
			   
			   
	       </div>
	     </div>

       	<div class="row form-group">
	       <div class="col-md-12 mb-3 mb-md-0">
	         <label class="font-weight-bold" for="fullname">Enter Kind <span style="color : red; font-size: 16px;" >*</span> </label>
					<select class="input-list" name="kind"   id="id_kind">
								<option value="new">New</option>
								<option value="used">Used</option>
		      </select>
	        </div>
	      </div>

        <div class="row form-group">
	       <div class="col-md-12 mb-3 mb-md-0">
	         <label class="font-weight-bold" for="fullname">Enter Kind <span style="color : red; font-size: 16px;" >*</span> </label>
					<select class="input-list" name="availability"  id="id_availability">
								<option value="instock">In stock</option>
								<option value="autofstock">Out Of stock</option>
								<option value="reqestorder">Request Order</option>
		      </select>
	        </div>
	      </div>

        
        <div class="row form-group">
	       <div class="col-md-12 mb-3 mb-md-0">
	         <label class="font-weight-bold" for="fullname">Select category <span style="color : red; font-size: 16px;" >*</span> </label>
					<select class="input-list" name="category"   id="id_category">
								<option value="men">Men</option>
								<option value="digtal">Digtal</option>
								<option value="food">Food</option>
								<option value="accesories">Accesories</option>
		      </select>
	        </div>
	      </div>

            
       <div class="row form-group">
	        <div class="col-md-12 mb-3 mb-md-0">
	         <label class="font-weight-bold" for="fullname">Upload Product Main Image<span style="color : red; font-size: 16px;" >*</span> </label>
	         {{form.image}}
	      </div>
	    </div>


		<br>
      <button type="submit" class="btn btn-success">Continue <i class="fa fa-arrow-circle-right"></i></button>
    </form>


              {% if form.errors %}
              <div class="alert alert-danger text-center">
                <b> Error ! Change few things. </b>
                  {{form.errors}}
             
              </div>
              {% endif %}


				 <br>
				</div>
				<div class="col-md-2">ads
	         	</div>


		

	         </div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->
		<!-- /section -->
  	<script>
		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].className = 'form-control';
		form_fields[2].className = 'form-control';
		form_fields[3].className = 'form-control';
		form_fields[4].className = 'form-control';
		form_fields[5].className = 'form-control';
		form_fields[6].className = 'form-control';
		form_fields[7].className = 'form-control';

    
    for (var field in form_fields){	
			form_fields[field].placeholder +='These Filed requred';
		}


	</script>
	
	{% endblock %}